Repository HadoukenIO/core, pull requests merged in 2018-11, with the labels that each got.

#602 RUN-4480: no API injection for Chrome pages
  src/browser/api/application.js
Labels: cla-present, enable_chromium

#606 RUN-4480: more PR feedbacks
  src/browser/api/application.js
Labels: cla-present

#607 RUN-4733 - Multi-Runtime Channels Bug
  src/browser/api_protocol/api_handlers/mesh_middleware.ts
  src/browser/api_protocol/transport_strategy/elipc_strategy.ts
  src/browser/api_protocol/transport_strategy/ws_strategy.ts
Labels: cla-present, hotfix, staging

#615 Feature/run 4106 multi runtime groups
  Gruntfile.js
  src/browser/api/application.js
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/window.ts
  src/browser/bounds_changed_state_tracker.ts
  src/browser/connection_manager.ts
  src/browser/disabled_frame_group_tracker.ts
  src/browser/remote_subscriptions.ts
  src/browser/window_groups.ts
  src/browser/window_groups_runtime_proxy.ts
  src/shapes.ts
Labels: cla-present

#618 RUN-4497 restrict group moves that break bounds
  src/browser/disabled_frame_group_tracker.ts
  src/browser/rectangle.ts
  test/rectangle.ts
Labels: AT started

#620 Merge 9.61.36/staging into master
  Gruntfile.js
  index.js
  npm-shrinkwrap.json
  package.json
  release.json
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/mesh_middleware.ts
  src/browser/api_protocol/transport_strategy/ack.ts
  src/browser/api_protocol/transport_strategy/api_transport_base.ts
  src/browser/api_protocol/transport_strategy/elipc_strategy.ts
  src/browser/api_protocol/transport_strategy/ws_strategy.ts
  src/browser/bounds_changed_state_tracker.js
  src/browser/bounds_changed_state_tracker.ts
  src/browser/convert_options.js
  src/browser/deferred.ts
  src/browser/port_discovery.ts
  src/browser/transports/chromium_ipc.ts
  src/browser/transports/unix_domain_socket.ts
  src/browser/window_group_transaction_tracker.ts
  src/common/errors.ts
  src/modules.d.ts
  src/renderer/api-decorator.js
Labels: cla-present

#621 Bump to 38
  release.json
Labels: auto testing started, cla-present

#604 RUN-4728 Send App Log API
  src/browser/api/application.js
  src/browser/api_protocol/api_handlers/application.js
Labels: auto testing done, cla-present

#611 RUN-4721: Make context menu settings updatable with UpdateOptions
  src/browser/api/window.js
Labels: auto testing ignore, cla-present, enable_chromium, staging

#624 Api group move
  src/browser/api_protocol/api_handlers/grouped_window_moves.ts
  src/browser/api_protocol/api_handlers/window.ts
  src/browser/disabled_frame_group_tracker.ts
  src/browser/normalized_rectangle.ts
  src/browser/rectangle.ts
Labels: auto testing done

#627 Merge staging into develop
  src/browser/api/window.js
Labels: cla-present

#629 Fixed multi runtime bounds changed
  src/browser/bounds_changed_state_tracker.ts
  src/browser/disabled_frame_group_tracker.ts
Labels: auto testing started

#630 always on and bring to front
  src/browser/core_state.ts
  src/browser/disabled_frame_group_tracker.ts
Labels: auto testing started

#626 Merge staging to develop 1.5
  src/browser/api/window.js
Labels: auto testing done, cla-present

#632 Fix build
  src/browser/bounds_changed_state_tracker.ts
Labels: cla-present

#633 Merge staging into window_groups
  src/browser/bounds_changed_state_tracker.ts
  src/browser/external_window_event_adapter.js
Labels: auto testing ignore, cla-present

#635 added min width for framed windows
  src/browser/normalized_rectangle.ts
Labels: auto testing ignore, cla-present

#636 Task no relocation on resize
  src/browser/rectangle.ts
Labels: auto testing ignore

#634 disabled disableFrame
  src/browser/api_protocol/api_handlers/grouped_window_moves.ts
Labels: auto testing ignore, cla-present

#640 Merge staging into develop
  src/browser/bounds_changed_state_tracker.ts
  src/browser/external_window_event_adapter.js
Labels: cla-present

#641 Don't remove all listeners in multi-runtime group-leave
  src/browser/window_groups_runtime_proxy.ts
Labels: auto testing ignore, cla-present

#645 only apply offset once on api moves
  src/browser/disabled_frame_group_tracker.ts
Labels: auto testing ignore, cla-present

#649 Fix for node-abi build issue
  npm-shrinkwrap.json
Labels: auto testing ignore, cla-present

#654 re-enable pushing of windows on resize in a group for set bounds
  src/browser/disabled_frame_group_tracker.ts
  src/browser/normalized_rectangle.ts
  src/browser/rectangle.ts
Labels: auto testing ignore, cla-present, hotfix, staging

#656 Merge staging into develop
  Gruntfile.js
  src/browser/api/application.js
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/grouped_window_moves.ts
  src/browser/api_protocol/api_handlers/window.ts
  src/browser/bounds_changed_state_tracker.ts
  src/browser/connection_manager.ts
  src/browser/disabled_frame_group_tracker.ts
  src/browser/normalized_rectangle.ts
  src/browser/rectangle.ts
  src/browser/remote_subscriptions.ts
  src/browser/window_groups.ts
  src/browser/window_groups_runtime_proxy.ts
  src/modules.d.ts
  src/shapes.ts
  test/rectangle.ts
Labels: auto testing started

#637 RVM-733: User-configurable flush interval for app logs
  src/browser/api/window.js
  src/browser/rvm/utils.ts
  src/shapes.ts
Labels: auto testing done, cla-present

#613 RUN-4677 - Channel lifecycle
  src/browser/api/channel.ts
  src/browser/api_protocol/api_handlers/channel.ts
Labels: auto testing done, cla-present

#639 RVM-747: Don't write console.debug to debug.log unless at least --v=1 given
  src/browser/api/window.js
Labels: auto testing done, cla-present

#659 Revert "RUN-4596, RUN-4742: Flag-protected cache migration"
  index.js
Labels: cla-present

#658 RUN-4783/made getFocusedWindow multi-runtime compatible
  src/browser/api_protocol/api_handlers/mesh_middleware.ts
  src/browser/api_protocol/api_handlers/system.ts
Labels: auto testing done, cla-present
