Repository HadoukenIO/core, pull requests merged in 2018-05, with the labels that each got.

#411 API V2 on by default.
  src/browser/convert_options.js
Labels: hotfix

#412 RUN-4118: add cachePath to getRuntimeInfo
  src/browser/api/system.js
Labels: hot-feature

#418 RUN-3981: override user_data & cache directory for MAC
  index.js
  src/browser/api/window.js
Labels: hotfix

#424 Merge staging into develop
  index.js
  src/browser/api/system.js
  src/browser/api/window.js
  src/browser/convert_options.js
Labels: cla-present

#410 RUN-4104: Add ability to mask RVM payloads; do so for application-log
  src/browser/rvm/rvm_message_bus.ts
  src/browser/rvm/utils.ts
  src/browser/transports/wm_copydata.ts
Labels: cla-present

#420 RUN-4143 - Emit Begin User Bounds Changing
  src/browser/bounds_changed_state_tracker.js
Labels: cla-present
