Repository HadoukenIO/core, pull requests merged in 2018-09, with the labels that each got.

#532 RUN-4438: System.getMachineId()
  src/browser/api/system.js
  src/browser/api_protocol/api_handlers/system.ts
Labels: cla-present

#524 RUN-4331 - Multiple channels for one identity
  src/browser/api/channel.ts
  src/browser/api_protocol/api_handlers/channel.ts
  src/browser/api_protocol/api_handlers/event_listener.js
  src/browser/api_protocol/api_handlers/mesh_middleware.ts
Labels: cla-present

#541 Merge staging into develop
  npm-shrinkwrap.json
  package.json
Labels: cla-present

#542 Updated the hadouken-js-adapter to 0.35.1-alpha.1
  npm-shrinkwrap.json
  package.json
Labels: cla-present

#537 RUN-4496 remove Object.entries polyfill; moved to NodeJS v8
  Gruntfile.js
Labels: cla-present

#539 RUN-4368 id undefined issue
  src/browser/api/application.js
Labels: cla-present

#534 RUN-4202 RUN-3435 Name iframes as default
  src/browser/api_protocol/transport_strategy/elipc_strategy.ts
  src/browser/convert_options.js
  src/renderer/api-decorator.js
Labels: cla-present

#531 RUN-4467 Remove Channels Remote Ack Map
  src/browser/api/channel.ts
  src/browser/api_protocol/api_handlers/mesh_middleware.ts
Labels: cla-present

#536 RUN-4512 Incremental change to organize elipc send responsibilities
  src/browser/api_protocol/transport_strategy/elipc_strategy.ts
Labels: cla-present

#545 RUN-4462 file download events
  index.js
  src/browser/api/file_download.ts
  src/browser/api_protocol/api_handlers/event_listener.js
  src/browser/convert_options.js
  src/browser/process_tracker.js
  test/electron.ts
  test/file_download.ts
Labels: cla-present, staging

#546 RUN-4565 - breadcrumb array is optional
  src/browser/api_protocol/transport_strategy/ack.ts
Labels: cla-present

#547 RUN-4566 - getAppAssetInfo always returns the error: "Cannot set property 'srcUrl' of undefined"
  src/browser/api_protocol/api_handlers/system.ts
Labels: cla-present

#548 Merge 9.61.34/staging into 9.61.35/staging
  index.js
  src/browser/api/file_download.ts
  src/browser/api_protocol/api_handlers/event_listener.js
  src/browser/api_protocol/api_handlers/system.ts
  src/browser/convert_options.js
  src/browser/process_tracker.js
  test/electron.ts
  test/file_download.ts
Labels: cla-present

#549 Merge staging into develop
  index.js
  src/browser/api/file_download.ts
  src/browser/api_protocol/api_handlers/event_listener.js
  src/browser/api_protocol/api_handlers/system.ts
  src/browser/convert_options.js
  src/browser/process_tracker.js
  test/electron.ts
  test/file_download.ts
Labels: cla-present

#556 RUN-4564: Use process object for build flag logs
  index.js
Labels: cla-present

#550 Run 4360 some fixes for our custom error boxes
  src/browser/api/window.js
  src/common/errors.ts
Labels: cla-present

#552 Bump electron rebuild to use 2.0.7
  Gruntfile.js
Labels: cla-present

#551 Specify the minimum node version via engines
  package.json
Labels: cla-present

#555 RUN-4533: Clean up abandoned file descriptors upon socket creation
  src/browser/transports/unix_domain_socket.ts
Labels: cla-present

#560 bump
  npm-shrinkwrap.json
  package.json
Labels: cla-present, staging

#558 RUN-4639 fix mac cache path to be more like windows
  index.js
Labels: cla-present

#563 Bump js-adapter to v.36
  npm-shrinkwrap.json
  package.json
Labels: cla-present

#526 RUN-4395/ Converted bounds_changed_state_tracker to typescript
  src/browser/api/window.js
  src/browser/bounds_changed_state_tracker.js
  src/browser/bounds_changed_state_tracker.ts
  src/browser/deferred.ts
  src/browser/window_group_transaction_tracker.ts
  src/modules.d.ts
Labels: cla-present

#562 RUN-4646 Download events with user-chosen name
  src/browser/api/file_download.ts
Labels: cla-present, hotfix, staging

#565 Merge 9.61.34/staging into 9.61.35/staging
  src/browser/api/file_download.ts
Labels: cla-present
