Repository HadoukenIO/core, pull requests merged in 2018-07, with the labels that each got.

#450 unsubscriptions.get is not a function exception
  src/browser/remote_subscriptions.ts
Labels: cla-present, hotfix

#457 Run 4184/event propagation
  index.js
  src/browser/api/system.js
  src/browser/api/window.js
  src/browser/navigation_validation.ts
  src/browser/of_events.ts
  test/event-propagation.ts
Labels: cla-present

#460 8.56.30/staging into 9.61.32/staging
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/window.js
Labels: cla-present

#447 RUN-4072 window restore fix for disconnected displays
  src/browser/animations.js
  src/browser/api/window.js
  src/browser/bounds_changed_state_tracker.js
  src/browser/clip_bounds.ts
  src/browser/deferred.ts
  src/browser/utils.ts
  src/modules.d.ts
Labels: cla-present

#441 RUN-4150: Emit session-changed event on MAC_OS
  src/browser/session.ts
  src/modules.d.ts
Labels: cla-present

#462 Merge 9.61.32/staging into develop
  README.md
  index.js
  src/browser/api/system.js
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/window.ts
  src/browser/navigation_validation.ts
  src/browser/of_events.ts
  src/browser/remote_subscriptions.ts
  test/event-propagation.ts
Labels: cla-present

#442 RUN-4195 cleaned up core's dependencies
  Gruntfile.js
  npm-shrinkwrap.json
  package.json
Labels: cla-present

#448 RUN-4032 - Fix for Application getInfo
  src/browser/api/application.js
  src/browser/core_state.ts
Labels: cla-present

#453 changed mocha test reporting
  Gruntfile.js
Labels: cla-present

#455 RUN-4239 updated TypeScript
  Gruntfile.js
  npm-shrinkwrap.json
  package.json
Labels: cla-present

#456 Prevent mockery noise
  test/errors.test.ts
  test/global_hotkey.tests.ts
  test/log.test.ts
  test/peer_connection_manager.tests.ts
  test/rvm_message_bus.test.ts
Labels: cla-present

#449 RUN-4241 - Fix undefined return when parent is in another runtime
  src/browser/core_state.ts
Labels: cla-present

#451 RUN-4237 fixed exceptions thrown for invalid monitor info
  src/browser/api/notifications/subscriptions.ts
  src/browser/monitor_info.js
Labels: cla-present

#454 removed repetitive grunt tasks
  Gruntfile.js
Labels: cla-present

#465 RUN-4211 Fixed notification ondismiss not working issue
  src/browser/api/notifications/subscriptions.ts
Labels: cla-present

#468 Made 'will-close' eveent public as 'closing'
  src/browser/api/window.js
Labels: cla-present, hotfix, staging

#464 RUN-4102 enable safe errors mode by default
  index.js
  src/common/errors.ts
Labels: cla-present

#466 RUN-4169 Bump electron-rebuild version and refactor
  Gruntfile.js
  npm-shrinkwrap.json
  package.json
Labels: cla-present

#469 Run-4184/don't propagate multiple close events
  src/browser/api/notifications/subscriptions.ts
  src/browser/api/window.js
  src/browser/subscription_manager.ts
  test/global_hotkey.tests.ts
Labels: cla-present, hotfix, regression, staging

#459 Update/fix tslint'ing
  Gruntfile.js
  package.json
  src/browser/api/frame.ts
  src/browser/api/global_hotkey.ts
  src/browser/api/notifications/subscriptions.ts
  src/browser/api_protocol/api_handlers/deprecated_external_windowing_middleware.ts
  src/browser/api_protocol/api_handlers/frame.ts
  src/browser/api_protocol/api_handlers/global_hotkey.ts
  src/browser/api_protocol/api_handlers/mesh_middleware.ts
  src/browser/api_protocol/api_handlers/service_middleware.ts
  src/browser/api_protocol/transport_strategy/api_transport_base.ts
  src/browser/api_protocol/transport_strategy/elipc_strategy.ts
  src/browser/connection_manager.ts
  src/browser/core_state.ts
  src/browser/remote_subscriptions.ts
  src/browser/transports/chromium_socket.ts
  src/browser/web_request_handler.ts
  test/errors.test.ts
  test/safe_int.tests.ts
  tslint.json
Labels: cla-present

#471 updated README
  README.md
Labels: cla-present

#467 Do not sign ofds files
  Gruntfile.js
Labels: cla-present

#472 Merge 9.61.32/staging into develop
  src/browser/api/notifications/subscriptions.ts
  src/browser/api/window.js
  src/browser/core_state.ts
  src/browser/subscription_manager.ts
  test/global_hotkey.tests.ts
Labels: cla-present

#474 Bump release.json to 34
  release.json
Labels: cla-present

#473 RUN-4100 safe errors UI improvements
  Gruntfile.js
  assets/error-icon.png
  assets/error.html
  src/common/errors.ts
  src/error/index.html
Labels: cla-present

#476 Merge 9.61.32/staging into master
  README.md
  index.js
  npm-shrinkwrap.json
  package.json
  release.json
  src/browser/api/application.js
  src/browser/api/global_hotkey.ts
  src/browser/api/interappbus.js
  src/browser/api/notifications/subscriptions.ts
  src/browser/api/service.ts
  src/browser/api/system.js
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/event_listener.js
  src/browser/api_protocol/api_handlers/global_hotkey.ts
  src/browser/api_protocol/api_handlers/mesh_middleware.ts
  src/browser/api_protocol/api_handlers/service.ts
  src/browser/api_protocol/api_handlers/service_middleware.ts
  src/browser/api_protocol/api_handlers/window.js
  src/browser/api_protocol/index.ts
  src/browser/bounds_changed_state_tracker.js
  src/browser/cached_resource_fetcher.ts
  src/browser/clip_bounds.ts
  src/browser/convert_options.js
  src/browser/core_state.ts
  src/browser/deferred.ts
  src/browser/navigation_validation.ts
  src/browser/of_events.ts
  src/browser/preload_scripts.ts
  src/browser/remote_subscriptions.ts
  src/browser/rvm/rvm_message_bus.ts
  src/browser/rvm/utils.ts
  src/browser/subscription_manager.ts
  src/browser/transports/wm_copydata.ts
  src/common/main.ts
  src/common/route.ts
  src/modules.d.ts
  src/renderer/api-decorator.js
  src/shapes.ts
  test/electron.ts
  test/event-propagation.ts
  test/global_hotkey.tests.ts
Labels: cla-present

#475 RUN-4267 transitioned system.js api handler to TypeScript
  src/browser/api_protocol/api_handlers/system.js
  src/browser/api_protocol/api_handlers/system.ts
  src/browser/api_protocol/index.ts
  src/browser/core_state.ts
  src/shapes.ts
Labels: cla-present

#480 RUN-4266 cannot-destructure-uuid-undefined
  src/browser/subscription_manager.ts
  test/global_hotkey.tests.ts
Labels: cla-present, hotfix

#483 RUN-4266 - Type protection in elipc
  src/browser/core_state.ts
Labels: cla-present, hotfix

#481 RUN-4310: Fix log rotation and process file deletion on OS X
  index.js
Labels: cla-present

#488 RUN-4316 application-initialized event now returns uuid
  src/renderer/api-decorator.js
Labels: cla-present, hotfix

#485 RUN-4269: Moved window teardown from 'closed' to 'will-close'
  src/browser/api/window.js
Labels: cla-present, hotfix

#489 RUN-4270 Runtime version on getInfo
  src/browser/api/application.js
  src/browser/api_protocol/api_handlers/mesh_middleware.ts
Labels: cla-present, hotfix

#487 RUN-4315 moved some files to assets
  Gruntfile.js
  assets/blank.ico
  assets/certificate.html
  assets/login.html
  index.js
  src/browser/api/window.js
  src/browser/authentication_delegate.ts
Labels: cla-present

#492 Merge 9.61.32/staging into 9.61.33/staging
  src/browser/api/application.js
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/mesh_middleware.ts
  src/browser/core_state.ts
  src/browser/subscription_manager.ts
  src/renderer/api-decorator.js
  test/global_hotkey.tests.ts
Labels: cla-present

#493 Merge 9.61.33/staging into develop
  src/browser/api/application.js
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/mesh_middleware.ts
  src/browser/core_state.ts
  src/browser/subscription_manager.ts
  src/renderer/api-decorator.js
  test/global_hotkey.tests.ts
Labels: cla-present

#478 RUN-4238: not override remote-debugging-port from ChromeDriver
  index.js
Labels: cla-present

#490 RUN-4322 getApplicationGroups should only return necessary properties
  src/browser/api_protocol/api_handlers/application.js
Labels: cla-present

#491 RUN-4329 Nested dependencies are not packaged
  Gruntfile.js
Labels: bug, cla-present

#497 README update
  README.md
Labels: cla-present

#494 RUN-4297 - fixed protocol, renamed to channels
  src/browser/api/channel.ts
  src/browser/api/service.ts
  src/browser/api_protocol/api_handlers/channel.ts
  src/browser/api_protocol/api_handlers/channel_middleware.ts
  src/browser/api_protocol/api_handlers/event_listener.js
  src/browser/api_protocol/api_handlers/service.ts
  src/browser/api_protocol/api_handlers/service_middleware.ts
  src/browser/api_protocol/index.ts
  src/browser/core_state.ts
  src/common/route.ts
  src/shapes.ts
Labels: cla-present

#498 RUN-4298 - Remove channels from middleware
  src/browser/api/channel.ts
  src/browser/api_protocol/api_handlers/channel.ts
  src/browser/api_protocol/api_handlers/channel_middleware.ts
  src/browser/api_protocol/api_handlers/deprecated_external_windowing_middleware.ts
  src/browser/api_protocol/index.ts
Labels: cla-present

#500 Fix error stemming from port discovery refactor
  src/browser/port_discovery.ts
Labels: hotfix

#499 RUN-4343 - Get all channels
  src/browser/api/channel.ts
  src/browser/api_protocol/api_handlers/channel.ts
  src/browser/api_protocol/api_handlers/mesh_middleware.ts
  src/shapes.ts
Labels: cla-present

#503 Merge 9.61.33/staging into develop
  src/browser/port_discovery.ts
Labels: cla-present

#502 bumped js-adapter to 0.34.1-alpha.2
  npm-shrinkwrap.json
  package.json
Labels: cla-present

#506 Merge 9.61.32/staging into master
  src/browser/api/application.js
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/mesh_middleware.ts
  src/browser/core_state.ts
  src/browser/subscription_manager.ts
  src/renderer/api-decorator.js
  test/global_hotkey.tests.ts
Labels: cla-present

#507 RUN-4332 move iframe out of experimental
  src/browser/convert_options.js
  src/renderer/main.js
  src/renderer/node-less.js
Labels: cla-present
