Repository HadoukenIO/core, pull requests merged in 2018-12, with the labels that each got.

#657 Remove rectangle offset
  src/browser/disabled_frame_group_tracker.ts
  src/browser/normalized_rectangle.ts
  src/browser/rectangle.ts
Labels: auto testing done, cla-present

#653 RVM-674: Add security realm to runtime => RVM payloads
  src/browser/rvm/rvm_message_bus.ts
  test/rvm_message_bus.test.ts
Labels: auto testing done, cla-present

#670 Merge staging into develop
  src/browser/cached_resource_fetcher.ts
Labels: cla-present

#665 RUN-4758 build fix
  Gruntfile.js
  package.json
Labels: auto testing done, cla-present

#672 RUN-4834 Updated Ack to send logId in a data payload.
  src/browser/api_protocol/api_handlers/application.js
Labels: auto testing done, cla-present

#669 RUN-4794 Fix js exception popup issue
  src/browser/api/system.js
  src/browser/cached_resource_fetcher.ts
  src/browser/core_state.ts
Labels: auto testing done, cla-present

#679 RUN-4846: cookie migration for enable_chromium
  index.js
Labels: auto testing ignore, cla-present

#673 RUN-4786 event subscription improvement
  src/browser/api/notifications/shapes.ts
  src/browser/api/notifications/subscriptions.ts
  src/browser/api_protocol/api_handlers/event_listener.js
  src/browser/api_protocol/api_handlers/event_listener.ts
  src/browser/api_protocol/index.ts
  src/browser/remote_subscriptions.ts
  src/common/main.ts
  src/shapes.ts
Labels: auto testing done, cla-present

#675 RUN-4819: mac main window close
  index.js
  src/browser/api/application.js
  src/browser/transports/unix_domain_socket.ts
Labels: auto testing done, cla-present

#676 RUN-4811/artificially raise end-user-bounds-changing
  src/browser/disabled_frame_group_tracker.ts
Labels: auto testing done, cla-present

#678 RUN-4829 naming change from 'frame' to 'userMovement'
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/window.ts
Labels: auto testing done, cla-present

#680 RUN-4786 event subscription improvement (Phase 2)
  src/browser/of_events.ts
  src/browser/remote_subscriptions.ts
  src/modules.d.ts
  test/electron.ts
  test/event-propagation.ts
Labels: auto testing ignore, cla-present, native-backed

#683 Spelling deferred
  src/browser/disabled_frame_group_tracker.ts
Labels: auto testing started, cla-present

#684 Merge staging into develop
  index.js
Labels: cla-present

#674 RUN-4649 RUN-4690 Only resize if within threshold region, handle fast resize events
  src/browser/api/window.js
  src/browser/disabled_frame_group_tracker.ts
  src/browser/rectangle.ts
  test/rectangle.ts
Labels: auto testing done, cla-present

#681 RUN-4816 disabled frame group now on by default
  src/browser/api_protocol/api_handlers/window.ts
  src/browser/bounds_changed_state_tracker.ts
  src/browser/window_groups.ts
  src/browser/window_groups_runtime_proxy.ts
Labels: auto testing done, cla-present

#682 RUN-4786 fixed remote subscriptions for System
  src/browser/of_events.ts
  src/browser/remote_subscriptions.ts
  src/common/main.ts
Labels: auto testing ignore, cla-present

#685 RUN-4855 fixed multi-runtime propagation
  src/browser/of_events.ts
  src/browser/remote_subscriptions.ts
Labels: auto testing done, cla-present

#687 Bump to 39
  release.json
Labels: cla-present

#686 RUN-4856 fix(external-windows): Emitting 'close' events for ExternalWindows
  src/browser/external_window_event_adapter.js
Labels: auto testing done, cla-present, staging

#691 RUN-4596, RUN-4742: Flag-protected cache migration
  index.js
Labels: auto testing ignore, cla-present, hot-feature, native-backed, staging

#692 RUN-4858 fixed setBounds when in group
  src/browser/disabled_frame_group_tracker.ts
Labels: auto testing ignore, cla-present, hotfix, staging

#693 RUN-4863 error handling and checks
  src/browser/disabled_frame_group_tracker.ts
  src/browser/window_groups_runtime_proxy.ts
Labels: auto testing ignore, cla-present
