Repository HadoukenIO/core, pull requests merged in 2018-10, with the labels that each got.

#566 Merge staging into develop
  src/browser/api/file_download.ts
Labels: cla-present

#574 Merge 9.61.34/staging into master
  Gruntfile.js
  README.md
  assets/blank.ico
  assets/certificate.html
  assets/error-icon.png
  assets/error.html
  assets/login.html
  index.js
  npm-shrinkwrap.json
  package.json
  release.json
  src/browser/api/application.js
  src/browser/api/channel.ts
  src/browser/api/external_application.ts
  src/browser/api/file_download.ts
  src/browser/api/frame.ts
  src/browser/api/global_hotkey.ts
  src/browser/api/service.ts
  src/browser/api/system.js
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/application.js
  src/browser/api_protocol/api_handlers/channel.ts
  src/browser/api_protocol/api_handlers/deprecated_external_windowing_middleware.ts
  src/browser/api_protocol/api_handlers/event_listener.js
  src/browser/api_protocol/api_handlers/global_hotkey.ts
  src/browser/api_protocol/api_handlers/mesh_middleware.ts
  src/browser/api_protocol/api_handlers/service.ts
  src/browser/api_protocol/api_handlers/service_middleware.ts
  src/browser/api_protocol/api_handlers/system.js
  src/browser/api_protocol/api_handlers/system.ts
  src/browser/api_protocol/index.ts
  src/browser/authentication_delegate.ts
  src/browser/convert_options.js
  src/browser/core_state.ts
  src/browser/plugins.ts
  src/browser/port_discovery.ts
  src/browser/preload_scripts.ts
  src/browser/process_tracker.js
  src/browser/remote_subscriptions.ts
  src/browser/rvm/rvm_message_bus.ts
  src/browser/transport.ts
  src/browser/transports/chromium_socket.ts
  src/browser/transports/unix_domain_socket.ts
  src/common/errors.ts
  src/common/route.ts
  src/error/index.html
  src/renderer/main.js
  src/renderer/node-less.js
  src/shapes.ts
  test/electron.ts
  test/file_download.ts
  tslint.json
Labels: cla-present

#578 RUN-4520: added experimental.chromeContextMenu (enable_chromium)
  src/browser/convert_options.js
  src/renderer/api-decorator.js
Labels: cla-present

#579 bump to 37
  release.json
Labels: cla-present

#564 Removed the need to specify any experimental flag in order to use the file download API
  index.js
  src/browser/convert_options.js
Labels: cla-present

#580 Feature/run 4462 file download non experimental
  index.js
  src/browser/convert_options.js
Labels: cla-present

#583 RUN-4460: Fix/v10/version
  Gruntfile.js
  npm-shrinkwrap.json
Labels: cla-present

#554 RUN-4538 explicit close of the download window on completion
  src/browser/api/file_download.ts
  src/modules.d.ts
  test/electron.ts
  test/file_download.ts
Labels: cla-present

#561 RUN-2315 added support for taking a snapshot of an area in a window
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/window.ts
Labels: cla-present

#569 RUN-4671 Fail on duplicate run calls
  src/browser/api_protocol/api_handlers/application.js
Labels: cla-present

#584 RUN-4636 fix for subscribeToAllRuntimes
  src/browser/remote_subscriptions.ts
Labels: cla-present

#568 RUN-4525: refine grouped window move on MAC
  src/browser/bounds_changed_state_tracker.ts
  src/modules.d.ts
Labels: cla-present

#586 RUN-4654: calling app.exit during delegated launch
  index.js
Labels: enable_chromium

#529 RUN-4378 Hash winposCache filename
  src/browser/api/window.js
Labels: cla-present

#591 Bugfix/run 4709 set model
  index.js
Labels: cla-present, staging

#593 Merge staging into develop
  index.js
Labels: cla-present

#595 Merge 9.61.35/staging into master
  Gruntfile.js
  npm-shrinkwrap.json
  package.json
  release.json
  src/browser/api/application.js
  src/browser/api/channel.ts
  src/browser/api/system.js
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/application.js
  src/browser/api_protocol/api_handlers/channel.ts
  src/browser/api_protocol/api_handlers/event_listener.js
  src/browser/api_protocol/api_handlers/interappbus.js
  src/browser/api_protocol/api_handlers/interappbus.ts
  src/browser/api_protocol/api_handlers/mesh_middleware.ts
  src/browser/api_protocol/api_handlers/system.ts
  src/browser/api_protocol/index.ts
  src/browser/api_protocol/transport_strategy/elipc_strategy.ts
  src/browser/bounds_changed_state_tracker.js
  src/browser/convert_options.js
  src/browser/runtime_p2p/peer_connection_manager.ts
  src/browser/transports/unix_domain_socket.ts
  src/browser/window_groups.js
  src/browser/window_groups.ts
  src/renderer/api-decorator.js
  src/shapes.ts
  tsconfig.json
Labels: cla-present

#582 RUN-4545 Fix js error: not opened at WebSocket.send
  src/browser/api_protocol/api_handlers/system.ts
  src/browser/api_protocol/transport_strategy/ws_strategy.ts
  src/browser/preload_scripts.ts
Labels: cla-present

#585 RUN-4708 Fixed hanging resolve-uuid
  src/browser/runtime_p2p/peer_connection_manager.ts
Labels: cla-present

#592 RUN-4718 - Port Discovery Fix
  src/browser/port_discovery.ts
  src/browser/transports/chromium_ipc.ts
Labels: cla-present

#596 RUN-4715 Fix window has incorrect zoom level issue when reopen
  src/browser/api/window.js
  src/renderer/api-decorator.js
Labels: cla-present, staging

#570 RUN-4670/Forward error message rather than error
  src/browser/api_protocol/transport_strategy/ack.ts
Labels: cla-present

#575 RUN-4679 not log password
  src/browser/api_protocol/transport_strategy/api_transport_base.ts
  src/browser/api_protocol/transport_strategy/elipc_strategy.ts
Labels: cla-present

#572 RUN-4443 Channel lifecycle / Cleanup
  src/browser/api/channel.ts
Labels: cla-present

#577 RUN-4684 - Multi Runtime Channel Nack
  src/browser/api/channel.ts
Labels: cla-present

#599 RUN-4718 - Port Discovery Fix (#592)
  src/browser/port_discovery.ts
  src/browser/transports/chromium_ipc.ts
Labels: cla-present

#543 RUN-4398: Enable chrome pages
  src/browser/api/application.js
  src/common/main.ts
Labels: cla-present, enable_chromium

#594 RUN-4717: Support devtools and reload as window options
  src/browser/api/window.js
  src/browser/convert_options.js
  src/browser/core_state.ts
  src/common/main.ts
  src/renderer/api-decorator.js
  src/shapes.ts
Labels: cla-present, enable_chromium

#603 Merge develop into v10/develop
  index.js
  release.json
  src/browser/api/application.js
  src/browser/api/channel.ts
  src/browser/api/file_download.ts
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/application.js
  src/browser/api_protocol/api_handlers/event_listener.js
  src/browser/api_protocol/api_handlers/system.ts
  src/browser/api_protocol/api_handlers/window.ts
  src/browser/api_protocol/transport_strategy/ack.ts
  src/browser/api_protocol/transport_strategy/api_transport_base.ts
  src/browser/api_protocol/transport_strategy/elipc_strategy.ts
  src/browser/api_protocol/transport_strategy/ws_strategy.ts
  src/browser/bounds_changed_state_tracker.ts
  src/browser/convert_options.js
  src/browser/core_state.ts
  src/browser/of_events.ts
  src/browser/port_discovery.ts
  src/browser/preload_scripts.ts
  src/browser/remote_subscriptions.ts
  src/browser/runtime_p2p/peer_connection_manager.ts
  src/browser/transports/chromium_ipc.ts
  src/common/main.ts
  src/common/route.ts
  src/modules.d.ts
  src/renderer/api-decorator.js
  src/shapes.ts
  test/electron.ts
  test/file_download.ts
Labels: cla-present

#605 Bump electron version to 3.0.6
  Gruntfile.js
Labels: cla-present
