Repository HadoukenIO/core, pull requests merged in 2019-07, with the labels that each got.

#851 build fix
  src/browser/api/external_window.ts
Labels: cla-present, hotfix

#839 RUN-5363: Enable Electron's unittests
  src/browser/convert_options.js
Labels: cla-present

#852 RUN-5248: Renderer crash when closing child windows
  src/browser/core_state.ts
  src/renderer/api-decorator.js
  src/renderer/main.js
  src/renderer/node-less.js
Labels: cla-present

#791 RUN-5291: Secure API for real phase 1
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/api_policy_processor.ts
  src/browser/api_protocol/api_handlers/system.ts
  src/browser/api_protocol/shapes.ts
  src/shapes.ts
Labels: auto testing done, cla-present

#821 RUN-5233 disabled external window frame
  src/browser/api/external_window.ts
  src/browser/api_protocol/api_handlers/external_window.ts
Labels: auto testing done, cla-present

#854 Add performance-report event
  src/renderer/api-decorator.js
Labels: auto testing done, cla-present

#857 RUN-5397: Update electron.d.ts to new intake version.
  src/electron.d.ts
Labels: auto testing ignore, cla-present

#858 Update unix-dgram to a version that works with Node 12
  npm-shrinkwrap.json
Labels: auto testing ignore, cla-present

#859 Remove code as per comment
  src/modules.d.ts
Labels: auto testing ignore, cla-present

#838 RUN-5360 Feature/browserview
  src/browser/api/browser_view.ts
  src/browser/api_protocol/api_handlers/browser_view.ts
  src/browser/api_protocol/api_handlers/middleware_entity_existence.ts
  src/browser/api_protocol/index.ts
  src/browser/core_state.ts
  src/shapes.ts
Labels: auto testing done, cla-present

#840 Run 5373 nwi allow non hwnd uuids
  src/browser/api/external_window.ts
Labels: auto testing done, cla-present

#841 [RUN-5208] Allow external connections to connect to a channel with a nameAlias field. Include the intendedTargetIdentity in dispatched messages so that external adapters can handle window addressing
  src/browser/api/channel.ts
Labels: auto testing done, cla-present

#842 RUN-5349 bug fix for disabled frames with alive requestors
  src/browser/api/window.js
Labels: auto testing done, cla-present

#860 RUN-5408: Updated electron.d.ts
  src/electron.d.ts
Labels: auto testing ignore, cla-present

#856 RUN-5305 Added reviewer and test link items to the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: auto testing done, cla-present

#848 RUN-5392 - group resize bugfix
  src/browser/bounds_changed_state_tracker.ts
  src/browser/rectangle.ts
  test/rectangle.ts
Labels: auto testing done, cla-present

#868 RUN-5409: Updated electron.d.ts
  src/electron.d.ts
Labels: auto testing ignore, cla-present

#870 RUN-5420: Keep reference to created context menu
  src/browser/api/window.js
Labels: auto testing ignore, cla-present

#874 RUN-5451: Fixed version of electron
  Gruntfile.js
Labels: cla-present

#869 Fix Channels API iFrame bug
  src/browser/api/channel.ts
  src/browser/core_state.ts
  src/shapes.ts
Labels: auto testing done, cla-present

#873 RUN-5420: Keep reference to created context menu (#870)
  src/browser/api/window.js
Labels: auto testing ignore, cla-present

#875 RUN-5439: Updated electron.d.ts
  src/electron.d.ts
Labels: auto testing ignore, cla-present

#877 RUN-5464: Updated electron.d.ts for Electron 6.0.0
  src/electron.d.ts
Labels: auto testing ignore, cla-present

#878 RUN-5461 - v43 regressions fix
  src/browser/api/window.js
Labels: auto testing ignore, cla-present, staging
