Repository HadoukenIO/core, pull requests merged in 2019-05, with the labels that each got.

#779 RUN-5242 Show a false warning message when there is a valid license key
  src/renderer/main.js
Labels: auto testing ignore, cla-present, hotfix

#772 RUN-5166 Add a custom lint rule in the core to prevent using 'fs' in favor of 'original-fs'
  Gruntfile.js
  test/lint-rules/.gitignore
  test/lint-rules/noFsRule.ts
  test/lint-rules/tsconfig.json
  tsconfig.json
  tslint.json
Labels: auto testing done, cla-present

#771 RUN-5197 experimental support for native windows
  src/browser/api/application.js
  src/browser/api/external_window.ts
  src/browser/api/system.js
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/api_protocol_base.ts
  src/browser/api_protocol/api_handlers/application.js
  src/browser/api_protocol/api_handlers/event_listener.ts
  src/browser/api_protocol/api_handlers/external_window.ts
  src/browser/api_protocol/api_handlers/grouped_window_moves.ts
  src/browser/api_protocol/api_handlers/system.ts
  src/browser/api_protocol/api_handlers/window.ts
  src/browser/api_protocol/index.ts
  src/browser/api_protocol/transport_strategy/elipc_strategy.ts
  src/browser/bounds_changed_state_tracker.ts
  src/browser/disabled_frame_group_tracker.ts
  src/browser/external_window_event_adapter.js
  src/browser/external_window_event_adapter.ts
  src/browser/normalized_rectangle.ts
  src/browser/transports/base.ts
  src/browser/transports/injection_bus.ts
  src/browser/transports/wm_copydata.ts
  src/browser/utils.ts
  src/browser/window_groups.ts
  src/common/main.ts
  src/common/route.ts
  src/common/windows_messages.ts
  src/modules.d.ts
  src/shapes.ts
Labels: auto testing done, cla-present

#787 Fix core build on windows
  Gruntfile.js
Labels: cla-present

#778 RUN-5189 Inject based on webcontents Id
  src/browser/core_state.ts
  src/renderer/main.js
  src/renderer/node-less.js
Labels: auto testing done, cla-present

#773 RUN-5112 Add the ability to get the desktop owner settings for services
  src/browser/api/system.js
  src/browser/api_protocol/api_handlers/system.ts
Labels: auto testing done, cla-present

#782 RUN-5200: Don't close window till content loaded - 10.66.41/staging
  src/browser/api/window.js
Labels: auto testing ignore, cla-present, hotfix

#788 RUN-5199: Changes introduced in electron v6.0.0 intake.
  index.js
  src/browser/api_protocol/api_handlers/authorization.js
  src/renderer/node-less.js
Labels: auto testing ignore, cla-present, v13

#780 [RUN-5071] Check for moveIndependently option in hijackMovesForGroupe…
  src/browser/api_protocol/api_handlers/grouped_window_moves.ts
Labels: auto testing done, cla-present

#792 RUN-5200: Hide window on close-requested
  src/browser/api/window.js
Labels: auto testing ignore, cla-present, hotfix

#785 RUN-5276 Add invalid license key info into debug log
  src/renderer/api-decorator.js
Labels: auto testing done, cla-present

#794 RUN-5200: revert changes
  src/browser/api/window.js
Labels: auto testing ignore, cla-present

#777 RUN-5060 : window.navigate should ack nack same as new fin...Window
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/window.ts
Labels: auto testing done, cla-present

#783 Run 5188/part 1
  src/browser/api/webcontents.ts
  src/browser/api/window.js
Labels: auto testing done, cla-present

#800 RUN-5314/added pid to unix_dgram name
  src/browser/transports/unix_domain_socket.ts
Labels: auto testing done, cla-present

#793 RUN-5294 Use non-primitive object type instead of boxed Object
  src/browser/api/notifications/shapes.ts
  src/browser/api/notifications/subscriptions.ts
  src/modules.d.ts
Labels: auto testing done, cla-present

#786 Run 5188/part 2
  src/browser/api_protocol/api_handlers/middleware_entity_existence.ts
  src/browser/api_protocol/api_handlers/webcontents.ts
  src/browser/api_protocol/api_handlers/window.ts
  src/browser/api_protocol/index.ts
Labels: auto testing done, cla-present

#798 RUN-5201: NWI: add docs tutorials for new API / events (partial)
  src/browser/api/external_window.ts
Labels: auto testing done, cla-present

#804 RUN-5297: Adapt code to upstream changes.
  src/browser/api/system.js
  src/browser/api/window.js
  src/browser/cached_resource_fetcher.ts
  src/electron.d.ts
Labels: auto testing ignore, cla-present
