Repository HadoukenIO/core, pull requests merged in 2019-08, with the labels that each got.

#879 Merge staging into develop
  src/browser/api/window.js
  src/electron.d.ts
Labels: cla-present

#880 Merge 13.76.43/staging to 13/develop
  src/browser/api/window.js
  src/electron.d.ts
Labels: auto testing ignore, cla-present

#862 RUN-5413 browser view iframes
  src/browser/api/browser_view.ts
  src/browser/api/frame.ts
  src/browser/api/webcontents.ts
  src/browser/api/window.js
  src/browser/core_state.ts
  src/modules.d.ts
  src/shapes.ts
Labels: auto testing done, cla-present

#881 RUN-5470 Join Group should Nack if given an "Native Window"
  src/browser/api_protocol/api_handlers/external_window.ts
  src/browser/api_protocol/api_handlers/window.ts
Labels: auto testing done, cla-present

#887 RUN-5472 - Application creation / run timing issue
  src/browser/api/application.js
Labels: auto testing started, cla-present

#882 Run 5463 nwi api security
  src/browser/api_protocol/api_handlers/external_window.ts
  src/browser/api_protocol/api_handlers/system.ts
Labels: auto testing done, cla-present

#872 Run 5449/run 5192 multi browser view
  src/browser/api/browser_view.ts
  src/browser/api_protocol/api_handlers/browser_view.ts
  src/browser/core_state.ts
  src/shapes.ts
Labels: auto testing done, cla-present

#864 RVM-946 Added GetInstalledRuntimes API
  src/browser/api/system.js
  src/browser/api_protocol/api_handlers/system.ts
  src/browser/rvm/rvm_message_bus.ts
Labels: auto testing done, cla-present

#888 RUN-5475 - Expose Electron's Window Centering API
  src/browser/api/native_window.ts
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/window.ts
Labels: auto testing done, cla-present

#890 fix(api-decorator): Make 'window/performance-report' ASYNC.
  src/renderer/api-decorator.js
Labels: auto testing ignore, cla-present

#891 Merge staging into develop
  src/renderer/api-decorator.js
Labels: cla-present

#895 [n/a] removed dead code that should not work
  src/browser/api/window.js
Labels: auto testing done, cla-present

#883 RUN-5456 There’s no way of programmatically telling if a window has enabled or disabled user movement
  src/browser/api/window.js
Labels: auto testing done, cla-present

#892 RUN-5414 browser process not exit when starting an app with duplicate UUID
  index.js
Labels: auto testing done, cla-present

#893 !A&!B !== !(A&B)
  src/browser/core_state.ts
Labels: auto testing done, cla-present

#894 RUN-5489 BrowserView name should be unique
  src/browser/api/browser_view.ts
Labels: auto testing done, cla-present

#897 RUN-5477: Updated electron.d.ts and modules.d.ts
  src/electron.d.ts
  src/modules.d.ts
Labels: auto testing ignore, cla-present

#900 RUN-5499: Updated electron.d.ts
  src/electron.d.ts
Labels: cla-present

#901 RUN-5484 Fix infinite message loop issue
  index.js
Labels: auto testing ignore, cla-present, staging

#902 Merge staging into develop
  index.js
Labels: cla-present

#905 chore: Update electron.d.ts for WinEVentHookEmitter changes
  src/electron.d.ts
Labels: auto testing done, cla-present

#904 chore(d.ts): Update electron.d.ts for WinEventHookEmitter changes
  src/electron.d.ts
Labels: auto testing ignore, cla-present

#906 RUN-5503 Should also check external connection with duplicate UUID
  index.js
  src/browser/api_protocol/api_handlers/application.js
Labels: auto testing done, cla-present

#899 RUN-5487 Resolve BrowserView in Webcontents api handler
  src/browser/api/browser_view.ts
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/middleware_entity_existence.ts
  src/browser/api_protocol/api_handlers/webcontents.ts
  src/browser/core_state.ts
Labels: auto testing done, cla-present

#885 RUN-5206 Set up webcontents eventing
  src/browser/api/webcontents.ts
  src/browser/api/window.js
Labels: auto testing done, cla-present

#910 RUN-5512 added finally block
  src/renderer/node-less.js
Labels: auto testing ignore, cla-present

#871 RUN-5309 - External window group moves
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/grouped_window_moves.ts
  src/browser/disabled_frame_group_tracker.ts
  src/browser/normalized_rectangle.ts
  src/browser/rectangle.ts
  src/browser/window_groups.ts
  test/rectangle.ts
Labels: auto testing done, cla-present

#912 Merge staging into develop
  src/renderer/node-less.js
Labels: cla-present

#913 Update grunt-contrib-jshint to 2.1.0 to allow for async/await
  .jshintrc
  npm-shrinkwrap.json
  package.json
Labels: auto testing done, cla-present

#911 RUN-5508: Reduce noise - only emit main win events
  src/browser/api/external_window.ts
Labels: auto testing done, cla-present

#914 RUN-5518 - Only bring to front on first move of grouped move
  src/browser/disabled_frame_group_tracker.ts
Labels: auto testing done, cla-present

#919 RUN-5579: Updated version of Electron which is used to build core
  Gruntfile.js
  npm-shrinkwrap.json
Labels: cla-present
