Repository HadoukenIO/core, pull requests merged in 2019-01, with the labels that each got.

#696 Merge v10/develop into develop
  Gruntfile.js
  npm-shrinkwrap.json
Labels: cla-present

#697 Bump to v10
  release.json
Labels: cla-present

#695 RVM-674: Add blank security realm to runtime => RVM payloads
  src/browser/rvm/rvm_message_bus.ts
Labels: auto testing done, cla-present

#705 RUN-4912 et al. fix(ipc-renderer): use internal IPC in nodeless sandbox renderer
  src/renderer/node-less.js
Labels: auto testing ignore, cla-present, native-backed, v11

#701 RUN-4909: api permission work for .39
  src/browser/api_protocol/api_handlers/application.js
  src/browser/api_protocol/api_handlers/system.ts
Labels: auto testing done, cla-present

#702 RUN-4933 Transition socket_server.js transport to socket_server.ts
  index.js
  package.json
  src/browser/api/system.js
  src/browser/api_protocol/api_handlers/authorization.js
  src/browser/api_protocol/transport_strategy/ws_strategy.ts
  src/browser/transports/socket_server.js
  src/browser/transports/socket_server.ts
Labels: auto testing done, cla-present

#711 Fix lint issues and missing shrinkwrap entry
  index.js
  npm-shrinkwrap.json
Labels: auto testing started, cla-present

#699 RUN-4893 fix(v11 core): upgrade rx to rxjs
  Gruntfile.js
  npm-shrinkwrap.json
  package.json
  src/browser/api/notifications/observable_sequences.ts
  src/browser/api/notifications/subscriptions.ts
  src/browser/api/window.js
  src/modules.d.ts
Labels: auto testing ignore, cla-present, v11

#706 RUN-4939 feat: move OS X single-tenant implementation to native code
  index.js
Labels: auto testing ignore, cla-present, native-backed

#703 RUN-3465 Read manifest file from rvm local cache folder
  src/browser/api/application.js
  src/browser/cached_resource_fetcher.ts
  src/browser/convert_options.js
Labels: auto testing done, cla-present

#710 RUN-4813 RUN-4814 RUN-4815 Propagate resizes through the window graph
  src/browser/disabled_frame_group_tracker.ts
  src/browser/rectangle.ts
  test/rectangle.ts
  tsconfig.json
Labels: auto testing done, cla-present

#713 Bump to 40
  release.json
Labels: cla-present
