Repository HadoukenIO/core, pull requests merged in 2019-04, with the labels that each got.

#755 Feature/RUN-5123 native window
  src/renderer/api-decorator.js
Labels: auto testing ignore, cla-present, new-api

#753 RUN-5130 Log system memory info on startup
  index.js
Labels: auto testing done, cla-present

#764 RUN-5170: Update code to upstream changes.
  src/renderer/api-decorator.js
  src/renderer/node-less.js
Labels: auto testing ignore, cla-present, v11

#762 Run 5149: Changes and fixes made in v12 intake to electron 5.0.0-beta.8.
  src/browser/api/native_window.ts
  src/browser/api/window.js
  src/renderer/api-decorator.js
  src/renderer/node-less.js
Labels: auto testing ignore, cla-present, v12

#765 Bump electron-rebuild version to 3.0.16
  Gruntfile.js
Labels: auto testing done, cla-present

#754 RUN-5069 Add window options updated event (take #2)
  src/browser/api/window.js
Labels: auto testing done, cla-present

#768 Merge Electron v4.1.4 into v11/develop
  src/renderer/api-decorator.js
  src/renderer/node-less.js
Labels: cla-present

#763 RUN-5134: Release uuid's on websocket disconnect
  src/browser/api_protocol/api_handlers/authorization.js
Labels: auto testing done, cla-present

#766 RUN-5109 Turn app log on by default.
  src/browser/api/window.js
Labels: auto testing done, cla-present

#769 Merge v11/develop into develop
  Gruntfile.js
  npm-shrinkwrap.json
  release.json
  src/renderer/api-decorator.js
  src/renderer/node-less.js
Labels: cla-present

#757 RUN-5084 - Proxy Window _options are not updated when the original window is.
  src/browser/window_groups_runtime_proxy.ts
Labels: auto testing done, cla-present

#770 RUN-5218 [Regression 10.66.41.*] Updating contextMenu window option has no effect
  src/browser/api/window.js
Labels: auto testing done, cla-present

#776 RUN-5223 added the args object to the getRuntimeInfo call
  src/browser/api/system.js
Labels: auto testing done, cla-present

#774 RUN-5180 updated types
  src/electron.d.ts
  src/modules.d.ts
Labels: auto testing done, cla-present
