Repository HadoukenIO/core, pull requests merged in 2019-02, with the labels that each got.

#718 RUN-4968 completely remove header logs
  src/browser/web_request_handler.ts
Labels: auto testing done, cla-present, staging

#708 RUN-4943 createFromManifest support for mac/linux
  src/browser/api/application.js
Labels: auto testing done, cla-present

#712 RUN-4955 rxjs update
  Gruntfile.js
  lib/rxjs/Rx.min.js
  npm-shrinkwrap.json
  package.json
  src/browser/api/notifications/observable_sequences.ts
  src/browser/api/notifications/subscriptions.ts
  src/browser/api/window.js
  src/modules.d.ts
Labels: auto testing done, cla-present

#726 Merge staging into develop
  src/browser/web_request_handler.ts
Labels: cla-present

#727 Lint fix
  src/renderer/api-decorator.js
Labels: auto testing ignore, cla-present, hotfix

#728 Merge staging into develop
  src/renderer/api-decorator.js
Labels: cla-present

#715 NWI initial intgration
  src/browser/api/native_window.ts
  src/browser/api/window.js
  src/browser/utils.ts
  src/modules.d.ts
  src/shapes.ts
Labels: auto testing done, cla-present

#723 Merge not handled for Target window
  src/browser/window_groups_runtime_proxy.ts
Labels: auto testing ignore, cla-present, hotfix

#729 Added guard
  src/browser/disabled_frame_group_tracker.ts
Labels: auto testing ignore, cla-present, hotfix

#720 RUN-4936 Fix for multi-runtime aggregate calls
  src/browser/api_protocol/api_handlers/mesh_middleware.ts
Labels: auto testing done, cla-present

#721 Feature/RUN-5024 multi runtime group merge
  src/browser/window_groups_runtime_proxy.ts
Labels: auto testing done, cla-present

#722 RUN-4958 Warning in console if no license key is included
  src/renderer/api-decorator.js
  src/renderer/main.js
Labels: auto testing done, cla-present

#731 RUN-4037 UUID enforcement
  index.js
  src/browser/api/application.js
  src/browser/api_protocol/api_handlers/application.js
  src/browser/api_protocol/api_handlers/authorization.js
  src/browser/api_protocol/api_handlers/mesh_middleware.ts
  src/browser/api_protocol/index.ts
  src/browser/core_state.ts
  src/browser/duplicate_uuid_delegation.ts
  src/browser/port_discovery.ts
  src/browser/runtime_p2p/peer_connection_manager.ts
  src/browser/transport.ts
  src/browser/uuid_availability.ts
Labels: auto testing done, cla-present

#733 RUN-4947 Undo clamp changes
  src/browser/utils.ts
Labels: auto testing done, cla-present

#734 added space
  src/renderer/api-decorator.js
Labels: auto testing done, cla-present

#736 log error message if dup uuid transport listener not unhooked properly
  src/browser/api_protocol/api_handlers/application.js
Labels: auto testing done, cla-present
