Repository HadoukenIO/core, pull requests merged in 2019-06, with the labels that each got.

#806 RUN-5270: Append meshUuis to injection bus msgs
  src/browser/transports/injection_bus.ts
Labels: auto testing done, cla-present

#802 RUN-5283 updated-types
  src/electron.d.ts
  src/modules.d.ts
Labels: auto testing done, cla-present

#803 RUN-5238 added missing info to "disabled-movement-bounds-changed"
  src/browser/api/external_window.ts
Labels: auto testing done, cla-present

#815 Revert "fixing navigateBack & navigateForward"
  src/browser/api/webcontents.ts
Labels: cla-present

#816 navigation bugfix
  src/browser/api/webcontents.ts
Labels: auto testing ignore, cla-present

#811 RUN-5253 change export type to es modules
  src/browser/animation/tween.js
  src/browser/animations.js
  src/browser/api/application.js
  src/browser/api/external_application.ts
  src/browser/api/interappbus.js
  src/browser/api/notification.js
  src/browser/api/system.js
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/application.js
  src/browser/api_protocol/api_handlers/authorization.js
  src/browser/bounds_changed_state_tracker.ts
  src/browser/convert_options.js
  src/browser/deferred.ts
  src/browser/external_window_event_adapter.ts
  src/browser/monitor_info.js
  src/browser/process_tracker.js
  src/browser/rvm/runtime_initiated_topics/rvm_info.js
Labels: auto testing started, cla-present

#812 Run 5254 Upgrade to Typescript 3.5
  npm-shrinkwrap.json
  package.json
  src/browser/api_protocol/api_handlers/grouped_window_moves.ts
Labels: auto testing failed, cla-present

#818 Fix readIntLE() call
  src/browser/session.ts
Labels: auto testing ignore, cla-present

#799 RUN-5265 cleaned up external window info object
  src/browser/api/external_window.ts
  src/browser/api/system.js
  src/browser/utils.ts
  src/shapes.ts
Labels: auto testing done, cla-present

#822 Merge staging into develop
  src/browser/api/webcontents.ts
Labels: cla-present

#801 RUN-5235 fixed "blurred" event for external windows
  src/browser/api/external_window.ts
  src/electron.d.ts
Labels: auto testing done, cla-present

#823 Bump electron-rebuild version to 4.2.0
  Gruntfile.js
Labels: auto testing done, cla-present

#817 RUN-5331: Resync electron type definitons and remove redundant ones.
  src/browser/animations.js
  src/browser/api/external_window.ts
  src/browser/api/system.js
  src/browser/api_protocol/api_handlers/clipboard.ts
  src/browser/external_window_event_adapter.ts
  src/browser/navigation_validation.ts
  src/browser/session.ts
  src/browser/transports/chromium_ipc.ts
  src/browser/utils.ts
  src/electron.d.ts
  src/modules.d.ts
  src/shapes.ts
Labels: auto testing ignore, cla-present

#824 RUN-5356 fix develop build
  src/browser/api/external_window.ts
Labels: cla-present

#827 Backport ts resync to v13 branch.
  src/browser/animations.js
  src/browser/api/system.js
  src/browser/api/webcontents.ts
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/clipboard.ts
  src/browser/external_window_event_adapter.ts
  src/browser/navigation_validation.ts
  src/browser/session.ts
  src/browser/transports/chromium_ipc.ts
  src/electron.d.ts
  src/modules.d.ts
  src/shapes.ts
Labels: auto testing ignore, cla-present

#828 RUN-5331: Update electron.d.ts with fixes after v13 backport.
  src/electron.d.ts
Labels: auto testing ignore, cla-present

#807 [RUN-5033] Windowing API calls nack if size constraints would be violated
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/window.ts
Labels: auto testing done, cla-present

#820 RUN-5350: Free app uuids on disconnect, not runtime
  src/browser/api_protocol/api_handlers/authorization.js
Labels: auto testing done, cla-present

#825 Run 5272 no non-existent hwnd
  src/browser/api/external_window.ts
Labels: auto testing done, cla-present

#829 RUN-5351: Regenerate electron.d.ts for intake.
  src/electron.d.ts
Labels: auto testing ignore, cla-present

#836 RUN-5362: Updated electron.d.ts (copied generated file from directory…
  src/electron.d.ts
Labels: auto testing ignore

#834 RUN-5366 fixes TS errors for external windows
  src/browser/api/external_window.ts
Labels: auto testing ignore, v13

#826 RUN-5358 Use webcontents id in ELIPC Strategy
  src/browser/api_protocol/api_handlers/api_protocol_base.ts
  src/browser/api_protocol/transport_strategy/api_transport_base.ts
  src/browser/api_protocol/transport_strategy/elipc_strategy.ts
  src/browser/core_state.ts
  src/modules.d.ts
  src/shapes.ts
Labels: auto testing done, cla-present

#830 RUN-5364: Update error to describe more cases
  src/browser/api/external_window.ts
Labels: auto testing done, cla-present

#846 RUN-5378: Update flash to newest version.
  index.js
Labels: cla-present

#847 RUN-5378: Update flash to newest version.
  index.js
Labels: cla-present

#845 RUN-5380 fixes window grouping regression
  src/browser/api/external_window.ts
  src/browser/api_protocol/api_handlers/grouped_window_moves.ts
  src/browser/window_groups.ts
Labels: cla-present, regression, staging, v11

#850 Merge staging into develop
  src/browser/api/external_window.ts
  src/browser/api_protocol/api_handlers/grouped_window_moves.ts
  src/browser/window_groups.ts
Labels: cla-present
