Repository HadoukenIO/core, pull requests merged in 2019-09, with the labels that each got.

#920 RUN-5309 Task/reintroduce transactions
  src/browser/disabled_frame_group_tracker.ts
Labels: cla-present, staging

#922 Added logging of cpu and memory usage around windowing and messaging
  src/browser/api_protocol/index.ts
  src/browser/api_protocol/transport_strategy/elipc_strategy.ts
  src/browser/api_protocol/transport_strategy/ws_strategy.ts
  src/browser/transports/socket_server.ts
Labels: auto testing ignore, cla-present

#908 Run 5493 native id refactor
  src/browser/api/external_window.ts
  src/browser/api_protocol/api_handlers/api_protocol_base.ts
  src/browser/utils.ts
  src/shapes.ts
Labels: auto testing done, cla-present

#909 RUN-5507 Switch to using webcontents id rather than browserwindow id
  index.js
  src/browser/api/application.js
  src/browser/api/file_download.ts
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/api_policy_processor.ts
  src/browser/api_protocol/api_handlers/application.js
  src/browser/api_protocol/api_handlers/authorization.js
  src/browser/api_protocol/api_handlers/deprecated_external_windowing_middleware.ts
  src/browser/convert_options.js
  src/browser/core_state.ts
  src/browser/navigation_validation.ts
  src/browser/web_request_handler.ts
  src/modules.d.ts
  src/renderer/api-decorator.js
Labels: auto testing done, cla-present

#917 RUN-5469 BrowserView state methods
  src/browser/api/application.js
  src/browser/api/browser_view.ts
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/application.js
  src/browser/api_protocol/api_handlers/browser_view.ts
  src/browser/api_protocol/api_handlers/window.ts
  src/browser/core_state.ts
Labels: auto testing done, cla-present

#932 RUN-5590: Updated electron.d.ts
  src/electron.d.ts
Labels: auto testing ignore, cla-present

#929 Develop to of master (via v14)
  .jshintrc
  index.js
  npm-shrinkwrap.json
  package.json
  release.json
  src/browser/api/application.js
  src/browser/api/browser_view.ts
  src/browser/api/external_window.ts
  src/browser/api/file_download.ts
  src/browser/api/webcontents.ts
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/api_policy_processor.ts
  src/browser/api_protocol/api_handlers/api_protocol_base.ts
  src/browser/api_protocol/api_handlers/application.js
  src/browser/api_protocol/api_handlers/authorization.js
  src/browser/api_protocol/api_handlers/browser_view.ts
  src/browser/api_protocol/api_handlers/deprecated_external_windowing_middleware.ts
  src/browser/api_protocol/api_handlers/grouped_window_moves.ts
  src/browser/api_protocol/api_handlers/middleware_entity_existence.ts
  src/browser/api_protocol/api_handlers/webcontents.ts
  src/browser/api_protocol/api_handlers/window.ts
  src/browser/convert_options.js
  src/browser/core_state.ts
  src/browser/disabled_frame_group_tracker.ts
  src/browser/navigation_validation.ts
  src/browser/normalized_rectangle.ts
  src/browser/rectangle.ts
  src/browser/utils.ts
  src/browser/web_request_handler.ts
  src/browser/window_groups.ts
  src/electron.d.ts
  src/renderer/api-decorator.js
  src/renderer/node-less.js
  src/shapes.ts
  test/rectangle.ts
Labels: auto testing ignore, cla-present

#933 RUN-5537: Updated electron.d.ts
  src/electron.d.ts
Labels: auto testing ignore, cla-present

#936 Merge staging into develop
  src/browser/disabled_frame_group_tracker.ts
Labels: cla-present

#935 Run-5584 Multi runtime channel disconnect
  src/browser/api/channel.ts
  src/browser/api_protocol/api_handlers/event_listener.ts
Labels: auto testing ignore, cla-present

#943 RUN-5608 exposed view.destroy
  src/browser/api/browser_view.ts
  src/browser/api_protocol/api_handlers/browser_view.ts
Labels: auto testing done, cla-present

#946 RUN-5537: Always pass headers in onBeforeSendHeaders callback.
  src/browser/web_request_handler.ts
Labels: auto testing done, cla-present

#945 RUN-5537: Always pass headers in onBeforeSendHeaders callback.
  src/browser/web_request_handler.ts
Labels: auto testing ignore, cla-present

#944 RUN-5537: Always pass headers in onBeforeSendHeaders callback.
  src/browser/web_request_handler.ts
Labels: auto testing ignore, cla-present

#934 RUN-5606 chore: Bump electron-rebuild
  Gruntfile.js
  npm-shrinkwrap.json
Labels: auto testing done, cla-present

#942 RUN-5469 Added name to getCurrentViews
  src/browser/api/window.js
Labels: auto testing done, cla-present

#940 RUN-5516: task: Remove legacy configuration
  src/browser/convert_options.js
Labels: auto testing done, cla-present

#949 RVM-976: createFromManifest changes
  src/browser/api/application.js
  src/browser/api_protocol/api_handlers/application.js
Labels: auto testing ignore, cla-present

#951 Browser view entity type
  src/browser/core_state.ts
  src/shapes.ts
Labels: auto testing done, cla-present

#954 RUN-5613: Updated electron.d.ts
  src/electron.d.ts
Labels: auto testing ignore, auto testing started, cla-present

#886 RUN-5454 window.getOptions does not return contentNavigation info
  src/browser/api/application.js
  src/browser/api/webcontents.ts
  src/browser/convert_options.js
  src/browser/navigation_validation.ts
Labels: auto testing done, cla-present

#931 RUN-5602 Use affinity for render process management of BrowserViews
  src/browser/api/browser_view.ts
Labels: auto testing done, cla-present

#948 [RUN-5206] Add BrowserView Method Events
  src/browser/api/browser_view.ts
  src/browser/api/frame.ts
  src/browser/api_protocol/api_handlers/event_listener.ts
  src/browser/remote_subscriptions.ts
  src/common/route.ts
Labels: auto testing done, cla-present

#938 RUN-5262 Uncaught js exception in main process
  src/browser/api/system.js
  src/browser/cached_resource_fetcher.ts
Labels: auto testing done, cla-present

#958 RUN-5629: Updated electron.d.ts and modules.d.ts
  src/electron.d.ts
  src/modules.d.ts
Labels: cla-present

#950 RUN-5604 Await loadUrl in browserview creation
  src/browser/api/browser_view.ts
Labels: auto testing done, cla-present

#964 RUN-5631: Updated electron.d.ts and modules.d.ts
  src/electron.d.ts
  src/modules.d.ts
Labels: cla-present

#956 RUN-5492 Throw error on window.open/fin.Window.create inside BrowserView
  src/renderer/api-decorator.js
Labels: auto testing done, cla-present

#965 RUN-4075 Add base64 support for setting tray icon
  src/browser/api/application.js
  src/browser/cached_resource_fetcher.ts
  src/common/main.ts
  test/base64.test.ts
Labels: auto testing done, cla-present, staging

#967 RUN-5641: Updated electron.d.ts and modules.d.ts
  src/electron.d.ts
  src/modules.d.ts
Labels: auto testing done, cla-present

#969 RUN-5645: Updated electron.d.ts
  src/electron.d.ts
Labels: auto testing done, cla-present

#937 RUN-5577 Logging for browserview
  src/browser/api/webcontents.ts
  src/browser/api/window.js
  src/browser/rvm/utils.ts
Labels: auto testing done, cla-present

#953 [RUN-5572] Standard frame prototype
  Gruntfile.js
  assets/frame/default-frame.html
  assets/frame/default-frame.js
  assets/frame/icons8-full-screen.svg
  assets/frame/icons8-horizontal-line.svg
  assets/frame/icons8-multiply.svg
  assets/frame/icons8-new-window.svg
  assets/frame/layout/goldenlayout-base.css
  assets/frame/layout/goldenlayout-dark-theme.css
  assets/frame/layout/goldenlayout.min.js
  assets/frame/layout/jquery-1.11.1.min.js
  assets/frame/layout/openfin-layout.js
  assets/frame/layout/resizable-view.js
  src/browser/api/application.js
  src/browser/convert_options.js
  src/shapes.ts
Labels: auto testing done, cla-present

#947 RUN-5534 fix: Execute preload scripts after API modules
  src/renderer/node-less.js
Labels: auto testing ignore, cla-present

#957 RUN-5468/ respect api permissions for browserviews
  src/browser/api_protocol/api_handlers/api_policy_processor.ts
Labels: auto testing done, cla-present

#959 Align "CONTRIBUTING" section in README.md to FINOS project blueprint
  README.md
Labels: auto testing done, cla-present

#960 [RUN-5625] Propagate events from BrowserView to Application and System
  src/browser/of_events.ts
Labels: auto testing done, cla-present

#961 Rearrage BrowserView Eventing During Creation
  src/browser/api/browser_view.ts
Labels: auto testing done, cla-present

#970 Bugfix - Call removeBrowserView on oldWin so that we can attach BrowserViews back and forth
  src/browser/api/browser_view.ts
Labels: auto testing done, cla-present

#962 RUN-5567 Added preloadscripts for browserviews
  src/browser/api/browser_view.ts
  src/browser/api/window.js
  src/browser/api_protocol/api_handlers/webcontents.ts
  src/browser/api_protocol/api_handlers/window.ts
  src/browser/core_state.ts
  src/browser/preload_scripts.ts
  src/browser/window_groups_runtime_proxy.ts
  src/shapes.ts
Labels: auto testing done, cla-present

#971 [RUN-5626] Emit view-attached and view-detached events from View to Window
  src/browser/api/browser_view.ts
Labels: auto testing done, cla-present

#968 [RUN-5628] Route WebContents events over to BrowserView
  src/browser/api/browser_view.ts
  src/browser/api/webcontents.ts
  src/browser/api/window.js
Labels: auto testing started, cla-present
